version: "3"
services:
  
  mongodb: 
    image: mongo:4.0.6
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    restart: unless-stopped
    volumes:
    - data:/data/db

  mongoapi:
    image: dschuldt/mongo-api:1.0
    container_name: mongoapi
    restart: unless-stopped
    ports:
    - "80:80"
    depends_on:
    - mongodb  
    
volumes:
  data:
