version: "3"
services:
  
  mongodb-standalone: 
    image: mongo:4.0.6
    container_name: mongodb-standalone
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    restart: unless-stopped
    ports:
    - 27017:27017  
    volumes:
    - mongodb-standalone:/data/db

volumes:
  mongodb-standalone:
